--------------------------------------------------------
--  File created - Friday-June-21-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNTDRILLVCS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACCOUNTDRILLVCS" 
   (	"EMAIL" VARCHAR2(90 BYTE), 
	"PASSWORD" VARCHAR2(90 BYTE), 
	"USER_TYPE" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ACCOUNTDRILLVCS
SET DEFINE OFF;
Insert into SYSTEM.ACCOUNTDRILLVCS (EMAIL,PASSWORD,USER_TYPE) values ('clinet@gmail.com','client','C');
Insert into SYSTEM.ACCOUNTDRILLVCS (EMAIL,PASSWORD,USER_TYPE) values ('admin@gmail.com','admin','A');
Insert into SYSTEM.ACCOUNTDRILLVCS (EMAIL,PASSWORD,USER_TYPE) values ('newuser@gmail.com','new','C');
Insert into SYSTEM.ACCOUNTDRILLVCS (EMAIL,PASSWORD,USER_TYPE) values ('user2@gmail.com','user2','C');
--------------------------------------------------------
--  DDL for Index ACCOUNTDRILLVCS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACCOUNTDRILLVCS_PK" ON "SYSTEM"."ACCOUNTDRILLVCS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ACCOUNTDRILLVCS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ACCOUNTDRILLVCS_TRG" 
BEFORE INSERT ON ACCOUNTDRILLVCS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."ACCOUNTDRILLVCS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNTDRILLVCS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACCOUNTDRILLVCS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCOUNTDRILLVCS" ADD CONSTRAINT "ACCOUNTDRILLVCS_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
